"""Capture privacy-safe internal visual QA screenshots from the real PyQt UI.

Outputs are written under the gitignored ``artifacts/visual_qa`` directory and
are never used as public product evidence.  The BEMS and drawing inputs are
synthetic, while every displayed KPI/finding is generated by production
services.
"""
from __future__ import annotations

import argparse
import os
import sys
import tempfile
from pathlib import Path

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import pandas as pd
from PyQt5.QtCore import QEventLoop, QTimer
from PyQt5.QtGui import QColor, QFont, QFontDatabase, QImage, QPainter, QPen
from PyQt5.QtWidgets import QApplication

from building_ai.config import Settings
from building_ai.models import AnalysisResult, SemanticResult
from building_ai.ui.context import ApplicationContext
from building_ai.ui.main_window import MainWindow
from building_ai.vision import DrawingDetection


PAGES = ("dashboard", "equipment", "energy_analysis", "analysis", "agent", "knowledge_base", "drawing_intelligence")
SIZES = ((1280, 720), (1440, 900), (1920, 1080))


def _events(app: QApplication, milliseconds: int = 120) -> None:
    loop = QEventLoop(); QTimer.singleShot(milliseconds, loop.quit); loop.exec_(); app.processEvents()


def _font(app: QApplication) -> None:
    windows_fonts = Path(os.environ.get("WINDIR", "")) / "Fonts"
    for path in (windows_fonts / "segoeui.ttf", windows_fonts / "msyh.ttc"):
        if not path.exists(): continue
        identifier = QFontDatabase.addApplicationFont(str(path)); families = QFontDatabase.applicationFontFamilies(identifier)
        if families: app.setFont(QFont(families[0], 10)); return


def _context(root: Path) -> ApplicationContext:
    context = ApplicationContext(Settings(provider="not_configured", language="en_US", data_dir=root / "runtime"))
    project = context.projects.create("Synthetic Building Study")
    context.current_project = project
    periods = 96
    context.dataframe = pd.DataFrame({
        "timestamp": pd.date_range("2026-07-01", periods=periods, freq="15min"),
        "AHP-01 Supply °C": [6.0 + (i % 8) * .03 for i in range(periods)],
        "AHP-01 Return °C": [8.1 + (i % 8) * .04 for i in range(periods)],
        "AHP-01 Flow m3/h": [18.0 + (i % 6) * .2 for i in range(periods)],
        "AHP-01 Power kW": [42.0 + (i % 12) * 1.1 for i in range(periods)],
    })
    specs = (
        ("AHP-01 Supply °C", "heat_source_supply_temp", "°C", "temperature"),
        ("AHP-01 Return °C", "heat_source_return_temp", "°C", "temperature"),
        ("AHP-01 Flow m3/h", "heat_source_flow", "m³/h", "volume_flow"),
        ("AHP-01 Power kW", "heat_source_power", "kW", "power"),
    )
    points = [SemanticResult(name, label, point_id=f"p-{index}", column=name, unit=unit, physical_quantity=quantity, equipment_id="AHP-01") for index, (name, label, unit, quantity) in enumerate(specs)]
    context.semantic_result = AnalysisResult(points, {item.raw_name: item.canonical_label for item in points})
    context.import_metadata = {"time_column": "timestamp", "start": "2026-07-01", "end": "2026-07-01 23:45"}
    context.equipment_organization = context.equipment_service.organize(project.project_id, points)
    context.equipment = context.equipment_organization.equipment
    context.run_diagnosis()

    drawing_path = root / "synthetic-layout.png"
    image = QImage(1100, 700, QImage.Format_RGB32); image.fill(QColor("#FAFCFF"))
    painter = QPainter(image); painter.setPen(QPen(QColor("#64748B"), 3))
    painter.drawRect(70, 70, 950, 550); painter.drawLine(550, 70, 550, 620); painter.drawRect(120, 170, 260, 160); painter.drawRect(700, 180, 210, 130); painter.end(); image.save(str(drawing_path), "PNG")
    drawing = context.drawings.import_drawing(project.project_id, drawing_path)
    detection = DrawingDetection("aircon", .93, 140, 190, 350, 310, 1100, 700)
    row = context.drawings.save_detections(project.project_id, drawing["drawing_id"], "synthetic-fake", [detection])[0]
    context.drawings.review_detection(project.project_id, row["detection_id"], "confirmed", "aircon")
    context.drawings.map_equipment(project.project_id, row["detection_id"], context.equipment[0].equipment_id)
    return context


def main() -> int:
    parser = argparse.ArgumentParser(); parser.add_argument("--scale", default="1.0"); args = parser.parse_args()
    os.environ.setdefault("QT_SCALE_FACTOR", args.scale)
    app = QApplication.instance() or QApplication(sys.argv)
    _font(app)
    with tempfile.TemporaryDirectory(prefix="buildingai-product-qa-") as value:
        context = _context(Path(value)); window = MainWindow(context); window.show(); _events(app)
        output = ROOT / "artifacts" / "visual_qa" / f"scale-{args.scale}"; output.mkdir(parents=True, exist_ok=True)
        for width, height in SIZES:
            window.resize(width, height); _events(app)
            for key in PAGES:
                payload = {"equipment_id": context.equipment[0].name} if key in {"equipment", "agent"} else {}
                window.navigate_to(key, payload); _events(app)
                if key == "analysis":
                    # Capture the investigation workbench, not only its KPI
                    # overview, so evidence boundaries are visually reviewed.
                    window.page_by_key["analysis"].tabs.setCurrentIndex(2); _events(app)
                destination = output / f"{width}x{height}-{key}.png"
                if not window.grab().save(str(destination), "PNG"):
                    raise RuntimeError(f"Could not save {destination}")
        window.close()
    print(f"Captured {len(PAGES) * len(SIZES)} privacy-safe QA screenshots at scale {args.scale}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
